package View;




import DAO.ProdutoDAO;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.Produto;



/**
 * Tela principal do sistema GameStorage.
 * 
 * Esta tela é responsável por exibir a lista de produtos cadastrados
 * no sistema através de uma JTable. Também permite acessar funções
 * como cadastro, edição e filtragem de produtos.
 * 
 * Funcionalidades principais:
 * - Exibir produtos cadastrados
 * - Filtrar produtos
 * - Abrir tela de cadastro
 * - Abrir tela de edição
 * 
 * @author Mateus
 */
public class TelaMain extends javax.swing.JFrame {
    
    
private String usuarioLogado;
 /**
 * Método responsável por carregar os produtos na JTable.
 * 
 * Utiliza o DefaultTableModel para inserir os registros
 * na tabela exibida na tela principal do sistema.
 * 
 * Esse método é chamado quando a tela é iniciada ou quando
 * é necessário atualizar os dados exibidos.
 */
private void carregarProdutos(){

    DefaultTableModel model = (DefaultTableModel) jTableProdutos.getModel();
    model.setRowCount(0);

    ProdutoDAO dao = new ProdutoDAO();

    for(Produto p : dao.listar()){
        model.addRow(new Object[]{
            p.getId(),
            p.getNome(),
            p.getCategoria(),
            p.getMarca(),
            p.getPreco(),
            p.getEstoque()
        });
    }
}

public void setUsuarioLogado(String usuario) {
    this.usuarioLogado = usuario;
    btnLogin.setEnabled(false);
}
public void configurarPermissoes(String tipo) {

    btnCadastrar.setVisible(false);
    btnEditar.setVisible(false);
    btnExcluir.setVisible(false);
    if (tipo.equals("funcionario")) {
        btnCadastrar.setVisible(true);
    }
    
    if (tipo.equals("gerente")) {
        btnCadastrar.setVisible(true);
        btnEditar.setVisible(true);
        btnExcluir.setVisible(true);
    }
    
}
 /**
 * Construtor da tela principal.
 * 
 * Inicializa todos os componentes gráficos da interface
 * e chama o método responsável por carregar os produtos
 * na tabela exibida na tela principal.
 */
    public TelaMain() {
        initComponents();
        carregarProdutos();
        btnCadastrar.setVisible(false);
        btnEditar.setVisible(false);
        btnExcluir.setVisible(false);
        btnLogin.setEnabled(true); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jCombHardware = new javax.swing.JComboBox<>();
        jCombPerifericos = new javax.swing.JComboBox<>();
        btnLogin = new javax.swing.JButton();
        txtFiltro = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProdutos = new javax.swing.JTable();
        btnMenu = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bem vindo a GameStorage");

        jLabel2.setBackground(new java.awt.Color(51, 153, 255));
        jLabel2.setFont(new java.awt.Font("Inter 18pt Light", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("GameStorage");
        jLabel2.setToolTipText("");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        jLabel2.setOpaque(true);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jCombHardware.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione um Hardware", "Placa Mãe", "Memória Ram", "CPU", "GPU", "Fontes", "Gabinetes", " ", " " }));
        jCombHardware.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCombHardwareActionPerformed(evt);
            }
        });

        jCombPerifericos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione um Periférico", "Teclado", "Monitores", "Mouse", "Fone" }));
        jCombPerifericos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCombPerifericosActionPerformed(evt);
            }
        });

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jCombHardware, javax.swing.GroupLayout.Alignment.TRAILING, 0, 222, Short.MAX_VALUE)
            .addComponent(jCombPerifericos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jCombHardware, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCombPerifericos, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 560, Short.MAX_VALUE)
                .addComponent(btnLogin)
                .addContainerGap())
        );

        txtFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFiltroActionPerformed(evt);
            }
        });

        jLabel1.setText("Pesuqise o Produto: ");

        jTableProdutos.setAutoCreateRowSorter(true);
        jTableProdutos.setFont(new java.awt.Font("Inter 18pt", 0, 12)); // NOI18N
        jTableProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Tipo", "Marca", "Preço", "Quantidade"
            }
        ));
        jTableProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProdutosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableProdutos);

        btnMenu.setBackground(new java.awt.Color(153, 153, 153));
        btnMenu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnMenu.setText("Atualizar");
        btnMenu.setToolTipText("Atualiza a tabela");
        btnMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        btnMenu.setOpaque(true);
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar Produto");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnCadastrar.setText("Cadastrar Produto");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCadastrar)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMenu))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnExcluir)
                            .addComponent(btnEditar)
                            .addComponent(btnCadastrar))
                        .addContainerGap())
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    /**
    * ComboBox utilizado para selecionar a categoria do produto.
    * 
    * As categorias disponíveis permitem classificar os produtos
    * cadastrados no sistema.
    */
    private void jCombHardwareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCombHardwareActionPerformed
  String categoria = jCombHardware.getSelectedItem().toString();

    // Se for "Todos", mostra tudo
    if (categoria.equals("Todos")) {
        carregarProdutos();
        return;
    }

    ProdutoDAO dao = new ProdutoDAO();
    List<Produto> lista = dao.buscarPorCategoria(categoria);

    DefaultTableModel modelo = (DefaultTableModel) jTableProdutos.getModel();
    modelo.setRowCount(0);

    for (Produto p : lista) {
        modelo.addRow(new Object[]{
            p.getId(),
            p.getNome(),
            p.getCategoria(),
            p.getMarca(),
            p.getPreco(),
            p.getEstoque()
        });
    }  
    }//GEN-LAST:event_jCombHardwareActionPerformed
    /**
    * Evento acionado ao selecionar uma categoria no ComboBox.
    * Filtra os produtos exibidos na tabela de acordo
    * com a categoria escolhida pelo usuário.
    */
    private void txtFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFiltroActionPerformed
  String nome = txtFiltro.getText();

    ProdutoDAO dao = new ProdutoDAO();
    List<Produto> lista = dao.buscarPorNome(nome);
    DefaultTableModel modelo = (DefaultTableModel) jTableProdutos.getModel();
    modelo.setRowCount(0); 

    for (Produto p : lista) {
        modelo.addRow(new Object[]{
            p.getId(),
            p.getNome(),
            p.getCategoria(),
            p.getMarca(),
            p.getPreco(),
            p.getEstoque()
        });
 }
    }//GEN-LAST:event_txtFiltroActionPerformed

    private void jCombPerifericosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCombPerifericosActionPerformed
String categoria = jCombPerifericos.getSelectedItem().toString();


    if (categoria.equals("Todos")) {
        carregarProdutos();
        return;
    }

    ProdutoDAO dao = new ProdutoDAO();
    List<Produto> lista = dao.buscarPorCategoria(categoria);

    DefaultTableModel modelo = (DefaultTableModel) jTableProdutos.getModel();
    modelo.setRowCount(0);

    for (Produto p : lista) {
        modelo.addRow(new Object[]{
            p.getId(),
            p.getNome(),
            p.getCategoria(),
            p.getMarca(),
            p.getPreco(),
            p.getEstoque()
        });
    }
    }//GEN-LAST:event_jCombPerifericosActionPerformed

    private void jTableProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProdutosMouseClicked



    }//GEN-LAST:event_jTableProdutosMouseClicked
    /**
     * Evento acionado ao clicar no botão Limpar Filtro.
     * 
     * Este método remove o filtro aplicado na tabela
     * de produtos, limpa o campo de busca e recarrega
     * todos os produtos na JTable.
     * 
     * @param evt evento de clique do botão
     */
    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
            
    txtFiltro.setText("");
    jCombPerifericos.setSelectedIndex(0);
    jCombHardware.setSelectedIndex(0);
    carregarProdutos();
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
    if (usuarioLogado != null) {
        javax.swing.JOptionPane.showMessageDialog(null, 
            "Você já está logado como: " + usuarioLogado);
    } else {
        new Login().setVisible(true);
        this.dispose();
    }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
      
    int linha = jTableProdutos.getSelectedRow();

    if (linha == -1) {
        javax.swing.JOptionPane.showMessageDialog(null, "Selecione um produto!");
        return;
    }

    int id = Integer.parseInt(jTableProdutos.getValueAt(linha, 0).toString());
    String nome = jTableProdutos.getValueAt(linha, 1).toString();
    String categoria = jTableProdutos.getValueAt(linha, 2).toString();
    String marca = jTableProdutos.getValueAt(linha, 3).toString();
    String preco = jTableProdutos.getValueAt(linha, 4).toString();
    String estoque = jTableProdutos.getValueAt(linha, 5).toString();

    EditarP tela = new EditarP();
    tela.setDados(id, nome, categoria, marca, preco, estoque);
    tela.setVisible(true);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int linha = jTableProdutos.getSelectedRow();

    if (linha == -1) {
        javax.swing.JOptionPane.showMessageDialog(null, "Selecione um produto!");
        return;
    }
    int confirm = javax.swing.JOptionPane.showConfirmDialog(
        null,
        "Tem certeza que deseja excluir?",
        "Confirmação",
        javax.swing.JOptionPane.YES_NO_OPTION
    );
    if (confirm == javax.swing.JOptionPane.YES_OPTION) {

        int id = Integer.parseInt(
            jTableProdutos.getValueAt(linha, 0).toString()
        );

        ProdutoDAO dao = new ProdutoDAO();
        dao.deletar(id);
        javax.swing.JOptionPane.showMessageDialog(null, "Produto excluído!");
        carregarProdutos(); 
    }
    
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
CadastroP tela = new CadastroP();
tela.setVisible(true);
    }//GEN-LAST:event_btnCadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnMenu;
    private javax.swing.JComboBox<String> jCombHardware;
    private javax.swing.JComboBox<String> jCombPerifericos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTableProdutos;
    private javax.swing.JTextField txtFiltro;
    // End of variables declaration//GEN-END:variables

}